
```{r Setting up libraries (a)}
setwd('/Users/burnssa/sites/data_analyst_nanodegree/nd_project_5/final_project')
getwd()
crimes <- read.csv('oakland_crimes.csv')
summary(crimes) #Output suppressed for final report
head(crimes) #to illustrate the available fields, with example values
#Include libraries - all critical to the analysis
#library(dplyr)
#library(ggplot2)
#install.packages("rjson")
#library("rjson")
#library(jsonlite)
#detach("rjson", TRUE)
remove.packages("rjson")
library(RJSONIO)
install.packages("data.table")
library(data.table)
installed.packages()

```

```{r Remove records with invalid latitude and longitude values}
crimes <- subset(crimes, (crimes$Lat < 40 & crimes$Lat > 37))
crimes <- subset(crimes, (crimes$Lng > -123 & crimes$Lng < -122.1 ))

```

```{r Remove records with invalid date values}
crimes <- subset(crimes, (as.Date(crimes$date_format) < as.Date('2015-08-01')))

```

```{r Cleaning up crimes csv}
#Remove 'NA' rows
clean_crimes_df <- na.omit(crimes)
write.csv(clean_crimes_df, file = "oakland_crimes_clean.csv")

```


```{r Add geojson file with neighborhoods}
neighborhood_data <- fromJSON('neighborhoods.geojson')

neighborhood_data[2]$features[[1]]
length((neighborhood_data[2]$features))

#"name" = str(), "type" = str(), "coordinates" = vector(),stringsAsFactors=FALSE

neighborhood_df <- data.frame(name = character(), type = character(), coordinates = as.list(character()),stringsAsFactors=FALSE)
colnames(neighborhood_df) <- c("name", "type", "coordinates")
as.list(neighborhood_df$coordinates)

i = 1
for(j in 1:(length(neighborhood_data[2]$features))){
    for(j in 1:(length(neighborhood_data[2]$features[[i]]$geometry$coordinates))){
      for(k in 1:(length(neighborhood_data[2]$features[[i]]$geometry$coordinates[[j]]))){
        #print(neighborhood_data[2]$features[[i]]$geometry$coordinates[[j]][[k]])
        c(neighborhood_df$coordinates[j][k],neighborhood_data[2]$features[[i]]$geometry$coordinates[[j]][[k]])
      }
      #print(as.character(neighborhood_data[2]$features[[i]]$geometry$coordinates[[j]][[k]]))
        #if(length(neighborhood_df$coordinates[j][k]) == 0) { neighborhood_df$coordinates[j][k] <- vector() }
        #as.neighborhood_df$coordinates[j][k]
        
  }
}

as.array

append(neighborhood_df$coordinates[1],3)

i = 1

typeof(neighborhood_df$coordinates)

  
  coordinates <- 
    
    
  newrow
  
neighborhood_df$name[[i] <- c(neighborhood_data[2]$features[[i]]$properties[i]) 
  #neighborhood_df$type[i] <- str(neighborhood_data[2]$features[[i]]$geometry$type)
#  for(j in 1:(length(neighborhood_data[2]$features[[i]]$geometry$coordinates))){
#    j = j + 1
#    k = 1
#   
#    }
#  }
}

head(neighborhood_df)

```



